
const evaReorts =  "Ethylene Vinyl Acetate’s Environmental and Economic Impact\n" +
"\n" +
"My Enviro-Me object is my Asics Torrance running shoes I wear every day. To me, the most important part of a shoe is the midsole because it handles the comfort and absorbs the shock when your feet connect with the ground. EVA (ethylene vinyl acetate) is the foam material used in the midsole of my Asics Torrance Men’s running shoes according to Run Repeat and Stacey O’Connor at Runner Click. EVA is popular and also used by several running shoe brands like Nike, Adidas and Under Armor to make for a comfortable midsole.  \n" +
"EVA is obtained from the environment in many ways and is a rather complex manufacturing process, therefore, I will describe where and who is producing this EVA first. Since Asics has released their ASICS Corporation Primary Supplier List 2017, I was able to deduct that it is very likely the EVA inside my shoes came from “the worlds largest contract footwear-maker Pou Chen Corp” (Ting-Fang) because they are the only ones that provide a level of transparency about using EVA for their footwear manufacturing process. Pou Chen Corp claims on their website to be able to produce 300 million shoes every year! The chain does not end here because Yue Yuen Industrial (Holdings) Limited, a subsidiary of Pou Chen Corp is the company’s main footwear manufacturer. Pou Chen strategically uses Yue Yuen to disperse the industrial liabilities from each other. It is not only important to understand that the industrial giant Yue Yuen produces and uses large amounts of EVA in Asian Countries but, also how it is generally made before we can really conclude the environmental impact shoes’ midsoles like mine have on the environment. \n" +
"EVA can occur naturally in living plants, but it can be extracted in larger amounts from natural resources like petroleum. We need vinyl-acetate and ethylene to make our final product. For my shoes the ethylene “is produced by heating either natural gas, especially its ethane and propane components or petroleum to 800–900 °C, giving a mixture of gases from which, the ethylene is separated” (Carey). The CDC (Center for Disease Control) claims that vinyl-acetate usually obtained from factories and not naturally by plants. Now that we know where the ethylene comes from, we need to know how vinyl-acetate is made. The Journal of Catalysts states “The synthesis of vinyl acetate from ethylene, acetic acid, and oxygen over Pd-based catalysts is an important industrial process” (Han, 60). Ethylene is created by distilling oil and natural gas while acetic acid and oxygen are obtained from in a wide range of ways. With vinyl-acetate and ethylene, we need high-pressure tubular reactors like the ones ENI Versailles manages (Autoclave Technology 7) to make EVA. Making this compound EVA requires a lot of energy and this results in unwanted emissions, and habitat destruction and fragmentation to mine the natural resources.\n" +
"Knowing exactly where the natural resources came from for my personal Asics Torrance running shoes is near impossible because Pou Chen’s 2017 CSR report claims to have had 1547 raw material suppliers in 2017 and EVA manufacturing is done all around the world in many types of environments. Therefore, I would like to focus on the Yue Yuen factory in China’s province Guangdong, city Dongguan often referred to as the factory of the world. It has a subtropical humid climate and unfortunately due to all the factories the wildlife, and water safety has horribly impacted the environment since the late 1990s. EVA itself is a not considered harmful to humans according to Center for Disease Control and Prevention but, manufacturing it still releases harmful emissions which makes this the biggest concern.\n" +
"Yue Yuen is an example of how conditions for factory workers have improved in China. In the city of Dongguan at the Yue Yuen factory, they have experienced recent strikes. A major one in 2014 that Wong at Bloomberg reported had over 40,000 workers that went on strike because they wanted better pay and they got it. The company said that it would raise its employee costs by 31 million dollars a year to provide better social security to its employees for many this is their livelihood.\n" + "MLA Citations\n" +
    "\n" +
    "“2017 CSR Report Pou Chen Corporation.” 2017 Pcc Csr Report-En.pdf, 2017, www.pouchen.com/download/corp-governance/2017%20pcc%20csr%20report-en.pdf.\n" +
    "\n" +
    "“Asics Gel Torrance - Reviews by 214 Runners & Experts.” Sports Shoe Reviews, runrepeat.com/asics-gel-torrance\n" +
    "\n" +
    "Carey, Francis A. “Ethylene.” Encyclopædia Britannica, Encyclopædia Britannica, Inc., 8 Apr. 2018, www.britannica.com/science/ethylene..\n" +
    "\n" +
    "“Ethylene Vinyl Acetate Copolymers High Pressure Tubular / Autoclave Technology.” ENI, ENI Versalis, www.versalis.eni.com/irj/go/km/docs/versalis/Contenuti%20Versalis/IT/Documenti/La%20nostra%20offerta/Licensing/Polietilene/ESE_Tecniche_EVA_1111.pdf.\n" +
    "\n" +
    "“Environmental, Social and Governance Report.” Yue Yuen, Yue Yuen Industrial (Holdings) Limted, 2016, www.yueyuen.com/images/hk/ESG/Eng/2016%20ESG%20Report_Eng.pdf.\n" +
    "\n" +
    "Han , Y.-F., et al. “Kinetics of Ethylene Combustion in the Synthesis of Vinyl Acetate over a Pd/SiO2 Catalyst.” Department of Chemistry | Texas A&M University, Journal of Catalysis 224 (2004) 60–68, 17 Feb. 2004, www.chem.tamu.edu/rgroup/goodman/pdf%20files/442_joc-224-04-60.pdf.\n" +
    "\n" +
    "O'Connor, Stacey. “Asics Gel Contend 4 Review - To Buy or Not in Oct 2018?” RunnerClick, runnerclick.com/asics-gel-contend-4-review/.\n" +
    "\n" +
    "“Public Health Statement for Vinyl Acetate.” Centers for Disease Control and Prevention, Agency for Toxic Substances and Disease Registry, 21 Jan. 2015, www.atsdr.cdc.gov/phs/phs.asp?id=669&tid=124.\n" +
    "\n" +
    "“SUPPLY CHAIN TRANSPARENCY.” ASICS Global, 2017, corp.asics.com/en/csr/suppliers_workers/transparency.\n" +
    "\n" +
    "Ting-Fang, Cheng. “Largest Nike Contractor Embroiled in Accounting Scandal.” Nikkei Asian Review, Nikkei Asian Review, 10 Jan. 2017, asia.nikkei.com/Business/Largest-Nike-contractor-embroiled-in-accounting-scandal.\n" +
    "\n" +
    "Wong, Stephanie. “Yue Yuen Resumes Production at Dongguan Factory After Strike.” Edited by Terje Langeland and Lena Lee, The Business of Fashion, 28 Apr. 2014, www.businessoffashion.com/articles/news-analysis/yue-yuen-resumes-production-dongguan-factory-strike.";

