import React, {Component} from 'react';
import Header from '../../Header'
import Footer from '../../Footer';
import PortfolioSlider from './PortfolioSlider'
import '../../../css/Pages/Portfolio/Portfolio.css';

export default class Portfolio extends Component{
    render() {
        return (
            <div>
                <Header/>
                <div className="large-animation-slider" id="sliding-container">
                    <PortfolioSlider title="State Fund"
                                     link="https://www.statefundca.com"
                                     content="I currently work at California State Compensation Insurance Fund as a student Assistant. I helped created standard operational procedures that kept my team compliant with internal and external financial and security audits. I Programed a Visual Basic Application to Scan through 200,000 Outlook Emails and generate a report with over 10,000 data sets of false positive security alerts generated by devices on the network."/>
                    <PortfolioSlider title="tCheck"
                                     link="https://www.tcheck.me"
                                     content="During my time at tCheck I became a skilled at Git Version Control by working in a small team of developers in a professional setting. I mostly programmed in Swift and React Native. This code I wrote was for Bluetooth communication, Authentication, Encryption, Network Requests. I also worked with some designers to make make the kind of GUI they wanted to see in the Android and iOS App."/>
                    <PortfolioSlider title="MHSOAC"
                                     link="http://www.mhsoac.ca.gov"
                                     content="During my time Mental Health Outlook and Accountability Commission I worked on the Organization’s Website to improve user experience. Setup new computers and printers to LAN, as well as a remote connection with personal accounts tied to a Microsoft 2016 Server. I also Utilized Command Prompt to diagnose internet connection issues and to remotely update several computers at once."/>
                    <PortfolioSlider title="My CC Insurance"
                                     link="TBD"
                                     content="This is currently my senior project and I am the leader for a group of 7 other guys. We are working on a Agency Management Software System for commercial insurance brokers. "/>
                </div>
                <Footer/>
            </div>
        );
    }
}
